language: python
sudo: false

python:
- 2.7
- 3.6

install:
- pip install -U -r build-requirements.txt
- python setup.py develop

script:
- pycodestyle .
- pyflakes .
- py.test --cov=former tests

after_success:
- coveralls
